apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHBqdGNiZjN4
  CLOUDINARY_KEY: OTExOTE5MjE2NzgzODg0
  CLOUDINARY_SECRET: X3JlRTkxeG9QTy1lNm1TTjVtbEhKQVZKbjhF
  MAPBOX_TOKEN: cGsuZXlKMUlqb2liR0ZzYVhSb1lTMWtaWFp2Y0hNaUxDSmhJam9pWTIxeE9XSjRlSFkxTURFNU1USndjalJrY21aaWEzbDFPU0o5LnRDZlREam92SWdnSlp4M0xvTXMxS2c=
  DB_URL: bW9uZ29kYitzcnY6Ly9sYWxpdGhhbnVrYWxhM19kYl91c2VyOmxhbGl0aGExMTIyQG15Y2x1c3Rlci5kN2FjczN4Lm1vbmdvZGIubmV0Lz9hcHBOYW1lPW15Y2x1c3Rlcg==
